# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 22:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0002_remove_userinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityquestion',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securityQuestion', to=settings.AUTH_USER_MODEL),
        ),
    ]
