# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 17:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(db_index=True, max_length=255)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('effect', models.ManyToManyField(blank=True, to='character.Effect')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='talent',
            field=models.ManyToManyField(to='character.Talent'),
        ),
    ]
