# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(default=5)),
                ('perception', models.IntegerField(default=5)),
                ('endurance', models.IntegerField(default=5)),
                ('charisma', models.IntegerField(default=5)),
                ('intelligence', models.IntegerField(default=5)),
                ('agility', models.IntegerField(default=5)),
                ('luck', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='OldJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('attributes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='character.Attributes')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='effect',
            name='type',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='talent',
            name='isPickable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='character',
            name='attributes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.Attributes'),
        ),
    ]
