# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_auto_20161215_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='effect',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='isPickable',
        ),
        migrations.AddField(
            model_name='character',
            name='oldJob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.OldJob'),
        ),
        migrations.AddField(
            model_name='oldjob',
            name='talent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.Talent'),
        ),
        migrations.AddField(
            model_name='talent',
            name='field',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='type',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='talent',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='effect',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='oldjob',
            name='attributes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.Attributes'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
