# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_auto_20161216_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='id',
            field=models.CharField(auto_created=True, db_index=True, default='', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
