# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_auto_20161216_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='id',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
        migrations.AddField(
            model_name='skill',
            name='requiredLv',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='skill',
            name='requiredSkill',
            field=models.ManyToManyField(null=True, to='character.Skill'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='id',
            field=models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
