# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_auto_20161216_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='effect',
            old_name='name',
            new_name='field',
        ),
    ]
