# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0009_auto_20170105_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='skill',
            field=models.ManyToManyField(to='character.Skill'),
        ),
    ]
