# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0010_character_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=0)),
                ('max_hp', models.IntegerField(default=0)),
                ('ap', models.IntegerField(default=0)),
                ('max_ap', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0.0)),
                ('weight_max', models.FloatField(default=0.0)),
                ('stamina', models.IntegerField(default=0)),
                ('max_stamina', models.IntegerField(default=0)),
                ('skillPoint', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('lv', models.IntegerField(default=0)),
                ('dodge_rate', models.FloatField(default=0.0)),
                ('hit_rate', models.FloatField(default=0.0)),
                ('crt_rate', models.FloatField(default=0.0)),
                ('crt_dmg', models.FloatField(default=0.0)),
                ('hunger', models.FloatField(default=0.0)),
                ('thirst', models.FloatField(default=0.0)),
                ('health', models.FloatField(default=0.0)),
                ('melee_dmg', models.IntegerField(default=0.0)),
                ('range_dmg', models.IntegerField(default=0.0)),
                ('energy_dmg', models.IntegerField(default=0.0)),
                ('persuade_rate', models.FloatField(default=0.0)),
                ('food_need', models.FloatField(default=0.0)),
                ('water_need', models.FloatField(default=0.0)),
                ('rest_rate', models.FloatField(default=0.0)),
                ('recover_rate', models.FloatField(default=0.0)),
                ('fire_resist', models.FloatField(default=0.0)),
                ('cold_resist', models.FloatField(default=0.0)),
                ('energy_resist', models.FloatField(default=0.0)),
                ('poison_resist', models.FloatField(default=0.0)),
                ('radiation_resist', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.Status'),
        ),
    ]
