# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0011_auto_20170111_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldjob',
            name='talent',
        ),
        migrations.AddField(
            model_name='oldjob',
            name='talent',
            field=models.ManyToManyField(to='character.Talent'),
        ),
    ]
