# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0013_auto_20170116_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='energy_dmg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='status',
            name='melee_dmg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='status',
            name='range_dmg',
            field=models.FloatField(default=0.0),
        ),
    ]
